version: '3.1'

services:

  strapi:
    container_name: megeve-cottage-api
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: mysql
      DATABASE_HOST: megeve-cottage-db
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: 'false'
    labels:
      - traefik.enable=true
      - traefik.http.services.MEGEVE_COTTAGE_API.loadbalancer.server.port=1337
      - traefik.http.routers.MEGEVE_COTTAGE_API.rule=Host(`api.megeve-cottage.com`)
      - traefik.http.routers.MEGEVE_COTTAGE_API.entrypoints=http
      - traefik.http.routers.MEGEVE_COTTAGE_API.middlewares=https-redirect@file
      - traefik.http.routers.MEGEVE_COTTAGE_API-Https.rule=Host(`api.megeve-cottage.com`)
      - traefik.http.routers.MEGEVE_COTTAGE_API-Https.entrypoints=https
      - traefik.http.routers.MEGEVE_COTTAGE_API-Https.middlewares=security@file, compression@file
      - traefik.http.routers.MEGEVE_COTTAGE_API-Https.tls=true
      - traefik.http.routers.MEGEVE_COTTAGE_API-Https.tls.certresolver=letsencrypt
    networks:
      - strapi
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - megeve-cottage-db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  megeve-cottage-db:
    image: mysql:5.7
    container_name: megeve-cottage-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'strapi'
      MYSQL_USER: 'strapi'
      MYSQL_PASSWORD: 'strapi'
      MYSQL_ROOT_PASSWORD: 'strapi'
    ports:
      - '3306:3306'
    volumes:
      - strapi-data:/var/lib/mysql
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    driver: bridge
