version: '3.1'

services:

  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi

  strapi:
    container_name: megeve-cottage-api
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: 'false'
    labels:
      - traefik.enable=true
      - traefik.http.services.MEGEVE_COTTAGE_API.loadbalancer.server.port=1337
      - traefik.http.routers.MEGEVE_COTTAGE_API.rule=Host(`api.megeve-cottage.com`)
      - traefik.http.routers.MEGEVE_COTTAGE_API.entrypoints=http
      - traefik.http.routers.MEGEVE_COTTAGE_API.middlewares=https-redirect@file
      - traefik.http.routers.MEGEVE_COTTAGE_API-Https.rule=Host(`api.megeve-cottage.com`)
      - traefik.http.routers.MEGEVE_COTTAGE_API-Https.entrypoints=https
      - traefik.http.routers.MEGEVE_COTTAGE_API-Https.middlewares=security@file, compression@file
      - traefik.http.routers.MEGEVE_COTTAGE_API-Https.tls=true
      - traefik.http.routers.MEGEVE_COTTAGE_API-Https.tls.certresolver=letsencrypt
    networks:
      - reverse-proxy
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - mysql

networks:
  reverse-proxy:
    external: true
